// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: models/stockfeed.proto

package stockfeed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdate) Reset() {
	*x = StockUpdate{}
	mi := &file_models_stockfeed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdate) ProtoMessage() {}

func (x *StockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_models_stockfeed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdate.ProtoReflect.Descriptor instead.
func (*StockUpdate) Descriptor() ([]byte, []int) {
	return file_models_stockfeed_proto_rawDescGZIP(), []int{0}
}

func (x *StockUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StockUpdate) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_models_stockfeed_proto protoreflect.FileDescriptor

const file_models_stockfeed_proto_rawDesc = "" +
	"\n" +
	"\x16models/stockfeed.proto\x12\tstockfeed\"A\n" +
	"\vStockUpdate\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05priceB+Z)warwickcodingsociety.com/models/stockfeedb\x06proto3"

var (
	file_models_stockfeed_proto_rawDescOnce sync.Once
	file_models_stockfeed_proto_rawDescData []byte
)

func file_models_stockfeed_proto_rawDescGZIP() []byte {
	file_models_stockfeed_proto_rawDescOnce.Do(func() {
		file_models_stockfeed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_stockfeed_proto_rawDesc), len(file_models_stockfeed_proto_rawDesc)))
	})
	return file_models_stockfeed_proto_rawDescData
}

var file_models_stockfeed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_stockfeed_proto_goTypes = []any{
	(*StockUpdate)(nil), // 0: stockfeed.StockUpdate
}
var file_models_stockfeed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_stockfeed_proto_init() }
func file_models_stockfeed_proto_init() {
	if File_models_stockfeed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_stockfeed_proto_rawDesc), len(file_models_stockfeed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_stockfeed_proto_goTypes,
		DependencyIndexes: file_models_stockfeed_proto_depIdxs,
		MessageInfos:      file_models_stockfeed_proto_msgTypes,
	}.Build()
	File_models_stockfeed_proto = out.File
	file_models_stockfeed_proto_goTypes = nil
	file_models_stockfeed_proto_depIdxs = nil
}
